version: '3.8'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: custom_ai_brain_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: custom_ai_brain
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
